Compiling 3 files (.ex)
Compiling 3 files (.ex)
Generated cadet app
cadet: generated priv/static/swagger.json

01:03:16.715 [info] Migrations already up
Running ExUnit with seed: 184121, max_cases: 44

.............................[ASSESSMENT_SUBMISSION] SENDING_OUT
.....[AVENGER_BACKLOG] course-level disabled
[AVENGER_BACKLOG] SENDING_OUT
[AVENGER_BACKLOG] SENDING_OUT
.

  1) test Manage assets delete ok file (Cadet.Assets.AssetsTest)
     test/cadet/assets/assets_test.exs:31
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/model_delete_asset#2.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/1/testFolder/test.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=eb4636f36507f3438e88be438b49ac665c3dd7ee8469dcc7432853f4eb9c7ba6"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170319Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: assert Assets.delete_object(prefix(1), "testFolder", "test.png") === :ok
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:55: Cadet.Assets.Assets.delete_object/3
       test/cadet/assets/assets_test.exs:33: (test)



  2) test Manage assets access another course with 0 folder (Cadet.Assets.AssetsTest)
     test/cadet/assets/assets_test.exs:18
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/model_list_assets#2.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:get, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/?prefix=courses-dev%2F2%2FtestFolder%2F", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=3e2bfe468373c6b076b8795389ea54372078104e8433755851457ca9ae85d380"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170319Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: assert Assets.list_assets(prefix(2), "testFolder") === []
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (ex_aws 2.5.9) lib/ex_aws.ex:85: ExAws.request!/2
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:7: anonymous fn/4 in ExAws.S3.Lazy.stream_objects!/3
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:18: anonymous fn/2 in ExAws.S3.Lazy.stream_objects!/3
       (elixir 1.18.3) lib/stream.ex:1571: Stream.do_resource/5
       (elixir 1.18.3) lib/enum.ex:4515: Enum.map/2
       test/cadet/assets/assets_test.exs:20: (test)



  3) test Manage assets upload existing file (Cadet.Assets.AssetsTest)
     test/cadet/assets/assets_test.exs:37
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/model_upload_asset#1.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/1/testFolder/test2.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=13c15ffce68a98d964248228c70eede720fe0d78fb99662f0fd89b6a187e7fb6"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170320Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: assert Assets.upload_to_s3(
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:18: Cadet.Assets.Assets.upload_to_s3/4
       test/cadet/assets/assets_test.exs:39: (test)



  4) test Manage assets delete nonexistent file (Cadet.Assets.AssetsTest)
     test/cadet/assets/assets_test.exs:24
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/model_delete_asset#1.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/1/testFolder/test4.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=12083bf68aeedc6ceb05f9ab4e5c7bf69034aef06b99600594755aed667473aa"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170320Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: assert Assets.delete_object(prefix(1), "testFolder", "test4.png") ===
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:55: Cadet.Assets.Assets.delete_object/3
       test/cadet/assets/assets_test.exs:26: (test)



  5) test Manage assets accessible folder (Cadet.Assets.AssetsTest)
     test/cadet/assets/assets_test.exs:8
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/model_list_assets#1.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:get, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/?prefix=courses-dev%2F1%2FtestFolder%2F", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=3fa280761ada3502c164c277e7aaa3781a83db339553d456ec73e18732184bd4"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170320Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: assert Assets.list_assets(prefix(1), "testFolder") === [
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (ex_aws 2.5.9) lib/ex_aws.ex:85: ExAws.request!/2
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:7: anonymous fn/4 in ExAws.S3.Lazy.stream_objects!/3
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:18: anonymous fn/2 in ExAws.S3.Lazy.stream_objects!/3
       (elixir 1.18.3) lib/stream.ex:1571: Stream.do_resource/5
       (elixir 1.18.3) lib/enum.ex:4515: Enum.map/2
       test/cadet/assets/assets_test.exs:10: (test)



  6) test Manage assets upload ok file (Cadet.Assets.AssetsTest)
     test/cadet/assets/assets_test.exs:49
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/model_upload_asset#2.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/1/testFolder/test1.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=5364a5f81c7020737d88523c43daa502d6337034f8953925d11c3d3d2ac0439d"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170320Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: assert Assets.upload_to_s3(
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:18: Cadet.Assets.Assets.upload_to_s3/4
       test/cadet/assets/assets_test.exs:51: (test)

.................................................01:03:21.444 request_id=GHNTmk5EyRz9IDkAADfC [error] Failed to create course for user 7361: viewable is invalid
01:03:21.444 request_id=GHNTmk5EyRz9IDkAADfC [error] Invalid parameters provided by user 7361 while creating a course.
..01:03:21.456 request_id=GHNTmk96Kd29nP4AADgC [error] User 7363 has exceeded the limit of 5 admin courses.
.01:03:21.459 request_id=GHNTmk-pD6MfhdcAABMB [error] Failed to create course for user 7364: source_chapter source chapter and source variant must be present together; can't be blank
.01:03:21.459 request_id=GHNTmk-pD6MfhdcAABMB [error] Invalid parameters provided by user 7364 while creating a course.
01:03:21.462 request_id=GHNTmk_Wkn1ssGsAABNB [error] User record not found for user 7365 in course 29701
................................................01:03:22.199 request_id=GHNTmnvI_oX9Yp8AADsC [error] User record not found for user 7412 in course 29869
.01:03:22.202 request_id=GHNTmnvs2Bg53agAAAtH [error] Failed to update course configuration for course 29869: source_variant is invalid
..01:03:22.206 request_id=GHNTmnwy0jC9wigAAAvH [error] User record not found for user 7415 in course 29872
.................01:03:22.261 request_id=GHNTmn94bNTiTjEAAA6H [error] Failed to update course configuration for course 29888: source_chapter source chapter and source variant must be present together
..01:03:22.264 request_id=GHNTmn-qj43xDksAAA9E [error] User record not found for user 7433 in course 29890
..........01:03:22.290 request_id=GHNTmoEzrqBLWjYAAD1C [error] Team creation failed for assessment 15139 - duplicate students
.....01:03:22.323 request_id=GHNTmoMo0TImw0QAABFE [error] User record not found for user 7453 in course 29925
.01:03:22.331 request_id=GHNTmoOdXfk5HtMAABGE [error] Cannot delete team 207 - team has submitted answers
..01:03:22.345 request_id=GHNTmoSBEdG2BRoAAD9C [error] User record not found for user 7461 in course 29935
.01:03:22.351 request_id=GHNTmoTZKrxMEfQAAD-C [error] Team creation failed for assessment 15147 - students already assigned to teams
......01:03:22.364 request_id=GHNTmoWV5G0FRCAAABIE [error] Team creation failed for assessment 15148 - teams exceed maximum size
..01:03:22.369 request_id=GHNTmoXrndIDf3YAAEDC [error] User record not found for user 7472 in course 29956
.01:03:22.374 request_id=GHNTmoYvCJyQI1UAABJE [error] Team creation failed for assessment 15150 - students not enrolled in course
....01:03:22.377 request_id=GHNTmoZsN0WH2fMAAEHC [error] Failed to update research agreement for user 7477. Status: bad_request, Message: agreed_to_research is invalid.
.01:03:22.380 request_id=GHNTmoaNGkbGZX4AABKE [error] Failed to update game states for user 7478. Status: bad_request, Message: game_states is invalid.
.........01:03:22.465 request_id=GHNTmouj56eiGZsAABQE [error] User 7489 is not enrolled in course 29997
.01:03:22.465 request_id=GHNTmouj56eiGZsAABQE [error] Failed to update latest viewed course for user 7489. Status: bad_request, Message: user is not in the course.
..........01:03:22.478 request_id=GHNTmoxq8LKyAZsAABRE [error] Failed to upload sourcecast for user 7492: title can't be blank
audio can't be blank
playbackData can't be blank
.............01:03:22.549 request_id=GHNTmpCh1KlKr24AABZE [error] Sourcecast 1 not found
...01:03:22.556 request_id=GHNTmpEOrZzDVVsAAEeC [error] User record not found for user 7524 in course 30042
..........01:03:23.067 request_id=GHNTmq-OQ5ctFOsAABQB [error] User record not found for user 7542 in course 30180
.......01:03:24.174 request_id=GHNTmvF4pV42OOcAABVB [error] Cannot delete story 78 - user not allowed to manage stories from another course
....01:03:24.191 request_id=GHNTmvJ6Qgl2BK0AAEoC [error] Cannot update story 80 - user not allowed to manage stories from another course
........01:03:24.212 request_id=GHNTmvO-cZH_0WMAAEuC [error] Failed to create story for course 30463: title can't be blank
close_at can't be blank
open_at can't be blank
filenames can't be blank
.

  7) test GET /v2/courses/:course_id/admin/generate-comments/:submissionid/:questionid errors out when given an invalid submission (CadetWeb.AICodeAnalysisControllerTest)
     test/cadet_web/controllers/ai_code_analysis_controller_test.exs:101
     ** (UndefinedFunctionError) function Cadet.Courses.Course.encrypt_llm_api_key/1 is undefined or private
     stacktrace:
       (cadet 0.0.1) Cadet.Courses.Course.encrypt_llm_api_key("test_key")
       test/cadet_web/controllers/ai_code_analysis_controller_test.exs:12: CadetWeb.AICodeAnalysisControllerTest.__ex_unit_setup_1/1
       test/cadet_web/controllers/ai_code_analysis_controller_test.exs:3: CadetWeb.AICodeAnalysisControllerTest.__ex_unit__/2



  8) test GET /v2/courses/:course_id/admin/generate-comments/:submissionid/:questionid LLM endpoint returns an invalid response - should log errors in database (CadetWeb.AICodeAnalysisControllerTest)
     test/cadet_web/controllers/ai_code_analysis_controller_test.exs:135
     ** (UndefinedFunctionError) function Cadet.Courses.Course.encrypt_llm_api_key/1 is undefined or private
     stacktrace:
       (cadet 0.0.1) Cadet.Courses.Course.encrypt_llm_api_key("test_key")
       test/cadet_web/controllers/ai_code_analysis_controller_test.exs:12: CadetWeb.AICodeAnalysisControllerTest.__ex_unit_setup_1/1
       test/cadet_web/controllers/ai_code_analysis_controller_test.exs:3: CadetWeb.AICodeAnalysisControllerTest.__ex_unit__/2



  9) test GET /v2/courses/:course_id/admin/generate-comments/:submissionid/:questionid success with happy path, admin and staff (CadetWeb.AICodeAnalysisControllerTest)
     test/cadet_web/controllers/ai_code_analysis_controller_test.exs:38
     ** (UndefinedFunctionError) function Cadet.Courses.Course.encrypt_llm_api_key/1 is undefined or private
     stacktrace:
       (cadet 0.0.1) Cadet.Courses.Course.encrypt_llm_api_key("test_key")
       test/cadet_web/controllers/ai_code_analysis_controller_test.exs:12: CadetWeb.AICodeAnalysisControllerTest.__ex_unit_setup_1/1
       test/cadet_web/controllers/ai_code_analysis_controller_test.exs:3: CadetWeb.AICodeAnalysisControllerTest.__ex_unit__/2

......01:03:24.243 [error] Failed to upsert achievement eb61dfa8-51c3-4b5d-89f8-3239de478c5d: course_id can't be blank
...................................................................................................................................................................???????01:03:51.816 [error] Cannot update course 32669 - course not found
01:03:51.817 [error] Failed to update course configuration for course 32669: source_chapter is invalid
01:03:51.818 [error] Failed to update course configuration for course 32669: source_variant is invalid


  9) Cadet.Auth.Providers.OpenIDTest: failure on setup_all callback, all tests have been invalidated
     ** (UndefinedFunctionError) function OpenIDConnect.Worker.start_link/1 is undefined (module OpenIDConnect.Worker is not available)
     stacktrace:
       OpenIDConnect.Worker.start_link([test: [discovery_document_uri: "http://localhost:43705/.well-known/openid-configuration", client_id: "dummy", client_secret: "dummydummy", response_type: "code", scope: "openid profile"]])
       test/cadet/auth/providers/openid/openid_test.exs:67: Cadet.Auth.Providers.OpenIDTest.__ex_unit_setup_all_0/1
       test/cadet/auth/providers/openid/openid_test.exs:1: Cadet.Auth.Providers.OpenIDTest.__ex_unit__/2

......................01:03:51.923 [error] Course 32701 not found
.......01:03:51.968 request_id=GHNToWn8V_7Cl2MAACsB [error] Failed to answer question 16779 - invalid parameters
01:03:51.971 request_id=GHNToWo3LEPCl2MAACvB [error] Failed to answer question 16778 - invalid parameters
01:03:51.978 request_id=GHNToWqXAmfCl2MAACwB [error] Invalid vote for question 16780 by user 8189
......01:03:52.134 request_id=GHNToXPjPpRZHc4AADFB [error] Failed to answer question 16798 - invalid parameters
01:03:52.137 request_id=GHNToXQfkqhZHc4AADGB [error] Failed to answer question 16797 - invalid parameters
01:03:52.143 request_id=GHNToXR2X6VZHc4AADHB [error] Invalid vote for question 16799 by user 8199
.....01:03:52.243 request_id=GHNToXpb0hjp8p8AADTB [error] Failed to answer question 16813 - invalid parameters
01:03:52.248 request_id=GHNToXqg0eXp8p8AADUB [error] Failed to answer question 16812 - invalid parameters
01:03:52.255 request_id=GHNToXsoZLHp8p8AADVB [error] Invalid vote for question 16814 by user 8207
..........01:03:52.445 request_id=GHNToYZ1N8IJtM4AADqB [error] Failed to answer question 16845 - submission already finalized
.........01:03:52.635 request_id=GHNToZHdDoc49jkAABbE [error] Login failed for provider 'test'.
.01:03:52.668 request_id=GHNToZPlm7-ESS8AACZD [error] SAML redirect failed for provider 'saml'.
01:03:52.684 request_id=GHNToZThD4VlPLwAADvB [error] Logout request failed due to missing parameters.
01:03:52.685 request_id=GHNToZTqZN5ByxwAABcE [error] Login failed for provider 'test'.
01:03:52.685 request_id=GHNToZTz5gcz2isAABdE [error] Invalid refresh token provided.


 10) test GET /auth/saml_redirect success (CadetWeb.AuthControllerTest)
     test/cadet_web/controllers/auth_controller_test.exs:104
     ** (RuntimeError) expected response with status 302, got: 500, with body:
     "Unknown error: Invalid or nonexistent provider config"
     code: assert response(conn, 302)
     stacktrace:
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:373: Phoenix.ConnTest.response/2
       test/cadet_web/controllers/auth_controller_test.exs:110: (test)

...01:03:52.713 request_id=GHNToZaS1TPB38cAABTF [error] SAML redirect failed for provider 'saml'.


01:03:52.726 request_id=GHNToZdZV8GHq9IAACaD [error] Refresh request failed due to missing parameters.
 11) test GET /auth/saml_redirect missing username attribute (CadetWeb.AuthControllerTest)
     test/cadet_web/controllers/auth_controller_test.exs:136
     ** (RuntimeError) expected response with status 400, got: 500, with body:
     "Unknown error: Invalid or nonexistent provider config"
     code: assert response(conn, 400) == "Unable to validate token: Missing username attribute!"
     stacktrace:
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:373: Phoenix.ConnTest.response/2
       test/cadet_web/controllers/auth_controller_test.exs:140: (test)

...01:03:52.751 request_id=GHNToZjTB4u9BmkAADxB [error] Invalid refresh token provided.
.01:03:52.774 request_id=GHNToZo2S_IetKQAADVG [error] SAML redirect failed for provider 'saml'.


 12) test GET /auth/saml_redirect missing name attribute (CadetWeb.AuthControllerTest)
     test/cadet_web/controllers/auth_controller_test.exs:129
     ** (RuntimeError) expected response with status 400, got: 500, with body:
     "Unknown error: Invalid or nonexistent provider config"
     code: assert response(conn, 400) == "Unable to validate token: Missing name attribute!"
     stacktrace:
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:373: Phoenix.ConnTest.response/2
       test/cadet_web/controllers/auth_controller_test.exs:133: (test)

.01:03:52.804 request_id=GHNToZwFd-HOmCoAADyB [error] Login failed for provider 'test'.
.01:03:52.813 request_id=GHNToZySFFocBfMAADzB [error] Login request failed due to missing parameters.
.01:03:52.814 request_id=GHNToZycOvc6H20AADWG [error] Invalid token provided for logout.
.01:03:52.837 request_id=GHNToZ34blUgJNsAABVF [error] SAML redirect request failed due to missing parameters.
..01:03:52.851 request_id=GHNToZ7NKHt-8qoAABWF [error] Invalid refresh token provided.
.01:03:52.872 request_id=GHNToaAOFW-TR0wAABXF [error] Login failed for provider 'test'.
.01:03:52.912 request_id=GHNToaI1e9IXrqAAACbD [error] SAML redirect failed for provider 'saml'.


 13) test GET /auth/saml_redirect missing SAML assertion (CadetWeb.AuthControllerTest)
     test/cadet_web/controllers/auth_controller_test.exs:122
     ** (RuntimeError) expected response with status 400, got: 500, with body:
     "Unknown error: Invalid or nonexistent provider config"
     code: assert response(conn, 400) == "Unable to validate token: Missing SAML assertion!"
     stacktrace:
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:373: Phoenix.ConnTest.response/2
       test/cadet_web/controllers/auth_controller_test.exs:126: (test)

.................................01:03:53.165 [error] Failed to enroll user 8202 in course 33061: role is invalid
.................................01:03:53.451 [error] No user found in conn.assigns.current_user, please check the AssignCurrentUser plug
..01:03:53.453 [error] Rate limit of 500 exceeded for user 1
.........01:03:53.586 request_id=GHNTocqFn5HTOpIAABoE [error] Device registration 101 not found for user 8321
.01:03:53.592 request_id=GHNTocrtQ5n2GAwAACjD [error] Device registration 103 not found for user 8322
....01:03:53.775 request_id=GHNTodWkWcOXgEcAABpE [error] Device registration 105 not found for user 8324
..........01:03:53.874 request_id=GHNTodvC06qXzaQAABrE [error] Device registration 107 not found for user 8327
....01:03:53.974 request_id=GHNToeG2rp80nvkAABeF [error] Failed to rename device registration 108: title can't be blank
...............01:03:54.085 request_id=GHNToegYNL-spbgAAEBB [error] User 8364 is not authorized to access conversation 9.
.01:03:54.085 request_id=GHNToegYNL-spbgAAEBB [error] Conversation not found for user 8364, conversation 9.
01:03:54.089 request_id=GHNToeiMruNxmcQAABsE [error] Conversation -1 not found for user 8366.
.01:03:54.089 request_id=GHNToeiMruNxmcQAABsE [error] Conversation not found for user 8366, conversation -1.
01:03:54.246 request_id=GHNTofHfN5t0i_EAAECB [error] User 8367 is not authorized to access conversation 10.
01:03:54.246 request_id=GHNTofHfN5t0i_EAAECB [error] Conversation not found for user 8367, conversation 10.
...01:03:54.439 request_id=GHNTof172nihNroAABgF [error] Section is missing for user 8370.
..01:03:54.444 request_id=GHNTof3CqxMzFHAAAEDB [error] Message too long for user 8371. Length: 1001.
.............................................01:04:08.228 [error] Cannot update story 86 - story not found
..01:04:08.231 [error] Cannot delete story 88 - user not allowed to manage stories from another course
.01:04:08.233 [error] Cannot delete story 90 - story not found
....01:04:08.239 [error] Cannot update story 96 - user not allowed to manage stories from another course
.......

 14) test course with custom assets_prefix upload file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:262
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_upload_asset#3.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/this-is-a-prefix/testFolder/nestedFolder/test.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=3b74e4c99c27399a00df997de8e7f7cb7b51e3000eea2b45d189e7300fb0414a"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170408Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: post(conn, build_url(course_id, "testFolder/nestedFolder/test.png"), %{
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:18: Cadet.Assets.Assets.upload_to_s3/4
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:42: CadetWeb.AdminAssetsController.upload/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/cadet_web/admin_controllers/admin_assets_controller_test.exs:269: (test)

.

 15) test ok request index file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:132
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_list_assets#1.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:get, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/?prefix=courses-dev%2F117%2FtestFolder%2F", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=83cd5736d311d1ece755eb34f0a86ef7d6f8a5d105191173d8a9cbb293794b62"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170408Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (ex_aws 2.5.9) lib/ex_aws.ex:85: ExAws.request!/2
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:7: anonymous fn/4 in ExAws.S3.Lazy.stream_objects!/3
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:18: anonymous fn/2 in ExAws.S3.Lazy.stream_objects!/3
       (elixir 1.18.3) lib/stream.ex:1571: Stream.do_resource/5
       (elixir 1.18.3) lib/enum.ex:4515: Enum.map/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:12: CadetWeb.AdminAssetsController.index/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (hackney 1.25.0) :hackney.request(:get, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/?prefix=courses-dev%2F117%2FtestFolder%2F", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=83cd5736d311d1ece755eb34f0a86ef7d6f8a5d105191173d8a9cbb293794b62"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170408Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}])



 16) test course with custom assets_prefix delete file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:249
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_delete_asset#3.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/this-is-a-prefix/testFolder/nestedFolder/test2.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=3ad6957b6c3a2a4891a6dc436a9e46b8355f4c0173f097ddf647bac419ef8eb0"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170408Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: conn = delete(conn, build_url(course_id, "testFolder/nestedFolder/test2.png"))
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:55: Cadet.Assets.Assets.delete_object/3
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:23: CadetWeb.AdminAssetsController.delete/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/cadet_web/admin_controllers/admin_assets_controller_test.exs:255: (test)

..

 17) test nested filename request delete file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:207
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_delete_asset#2.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/117/testFolder/nestedFolder/test2.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=f816c2b657d12b86c0030828709c8f725398e9af7eb25bf3b797b24ee7331950"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170409Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: conn = delete(conn, build_url(course_id, "testFolder/nestedFolder/test2.png"))
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:55: Cadet.Assets.Assets.delete_object/3
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:23: CadetWeb.AdminAssetsController.delete/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/cadet_web/admin_controllers/admin_assets_controller_test.exs:211: (test)



 18) test nested filename request upload file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:218
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_upload_asset#2.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/117/testFolder/nestedFolder/test.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=b276e93ad753e86da3b5d8b0b43472e3e465883a055dc9c1e6ab322cb9edf406"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170409Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: post(conn, build_url(course_id, "testFolder/nestedFolder/test.png"), %{
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:18: Cadet.Assets.Assets.upload_to_s3/4
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:42: CadetWeb.AdminAssetsController.upload/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/cadet_web/admin_controllers/admin_assets_controller_test.exs:223: (test)



 19) test ok request delete file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:144
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_delete_asset#1.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/117/testFolder/test2.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=65fc7089e1831b82570370dac1a3da6cfbd5b7a24db4e7f0e6e77d72323246c8"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170409Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: conn = delete(conn, build_url(course_id, "testFolder/test2.png"))
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:55: Cadet.Assets.Assets.delete_object/3
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:23: CadetWeb.AdminAssetsController.delete/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/cadet_web/admin_controllers/admin_assets_controller_test.exs:148: (test)

....

 20) test course with custom assets_prefix index file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:235
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_list_assets#2.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:get, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/?prefix=this-is-a-prefix%2FtestFolder%2F", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=54e3be18feab3eb2537292a44a21f14fb8a0ff99880af3dee7ec2f48cd3f3d1c"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170409Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (ex_aws 2.5.9) lib/ex_aws.ex:85: ExAws.request!/2
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:7: anonymous fn/4 in ExAws.S3.Lazy.stream_objects!/3
       (ex_aws_s3 2.4.0) lib/ex_aws/s3/lazy.ex:18: anonymous fn/2 in ExAws.S3.Lazy.stream_objects!/3
       (elixir 1.18.3) lib/stream.ex:1571: Stream.do_resource/5
       (elixir 1.18.3) lib/enum.ex:4515: Enum.map/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:12: CadetWeb.AdminAssetsController.index/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (hackney 1.25.0) :hackney.request(:get, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/?prefix=this-is-a-prefix%2FtestFolder%2F", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=54e3be18feab3eb2537292a44a21f14fb8a0ff99880af3dee7ec2f48cd3f3d1c"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170409Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}])

....

 21) test ok request upload file (CadetWeb.AdminAssetsControllerTest)
     test/cadet_web/admin_controllers/admin_assets_controller_test.exs:155
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixtures/vcr_cassettes/aws/controller_upload_asset#1.json.
     Delete the current cassette with [mix vcr.delete] and re-record.

     Request: [:head, "https://s3.ap-southeast-1.amazonaws.com/source-academy-assets/courses-dev/117/testFolder/test.png", [{"Authorization", "AWS4-HMAC-SHA256 Credential=hello/20251030/ap-southeast-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=26862231f49900869683bb7163788ff85fa166d6e89a3f192b6744b765aff03f"}, {"host", "s3.ap-southeast-1.amazonaws.com"}, {"x-amz-date", "20251030T170409Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}], "", [:with_body, {:recv_timeout, 660000}]]

     code: post(conn, build_url(course_id, "testFolder/test.png"), %{
     stacktrace:
       (exvcr 0.16.0) lib/exvcr/handler.ex:304: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       (exvcr 0.16.0) lib/exvcr/handler.ex:234: ExVCR.Handler.get_response_from_server/3
       (ex_aws 2.5.9) lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
       (ex_aws 2.5.9) lib/ex_aws/request.ex:115: anonymous fn/6 in ExAws.Request.do_request/7
       (telemetry 1.3.0) /home/tkai/source-academy/backend/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (ex_aws 2.5.9) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
       (ex_aws 2.5.9) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
       (cadet 0.0.1) lib/cadet/assets/assets.ex:72: Cadet.Assets.Assets.object_exists?/3
       (cadet 0.0.1) lib/cadet/assets/assets.ex:18: Cadet.Assets.Assets.upload_to_s3/4
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:42: CadetWeb.AdminAssetsController.upload/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.action/2
       (cadet 0.0.1) lib/cadet_web/admin_controllers/admin_assets_controller.ex:1: CadetWeb.AdminAssetsController.phoenix_controller_pipeline/2
       (phoenix 1.8.1) lib/phoenix/router.ex:416: Phoenix.Router.__call__/5
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint."call (overridable 3)"/2
       (cadet 0.0.1) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
       (phoenix 1.8.1) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/cadet_web/admin_controllers/admin_assets_controller_test.exs:160: (test)

..01:04:09.839 [error] Team creation failed for assessment 16932 - students not enrolled in course
..01:04:09.854 [error] Team creation failed for assessment 16936 - students already assigned to teams
.01:04:09.862 [error] Cannot delete team 281 - team has submitted answers
.01:04:09.866 [error] Team creation failed for assessment 16940 - duplicate students
.01:04:09.872 [error] Team creation failed for assessment 16943 - teams exceed maximum size
.01:04:09.877 [error] Team creation failed for assessment 16944 - duplicate students
...01:04:09.898 [error] Team creation failed for assessment 16950 - students not enrolled in course
......................................01:04:13.872 [error] Team not found for assessment 17673 and user 8870
.01:04:13.873 [error] Team not found for question 17549 and user 8870
.....01:04:14.477 [error] Team not found for assessment 17788 and user 8904
01:04:14.477 [error] Team not found for user 8904 in assessment 17788
........01:04:15.357 [error] Contest assessment not found
01:04:15.357 [error] Contest assessment not found
...........01:04:16.616 [error] Cannot delete assessment 18142 - contest voting is still active
................01:04:18.044 [error] Team not found for assessment 18411 and user 9131
01:04:18.044 [error] Team not found for user 9131 in assessment 18411
...01:04:18.616 [error] Failed to create question for assessment: type can't be blank
question can't be blank
library can't be blank
....01:04:19.495 [error] Force update failed: Question count is different
...........................01:04:23.952 request_id=GHNTqNx1BmXkEikAAHJB [error] Failed to retrieve assessment 19245 for user 9319: forbidden - Missing Password.
01:04:23.952 request_id=GHNTqNx1BmXkEikAAHJB [error] Error fetching assessment 19245 for user 9423: Missing Password. (status: forbidden).
01:04:23.954 request_id=GHNTqNydzlLkEikAAHLB [error] Failed to retrieve assessment 19245 for user 9318: forbidden - Missing Password.
01:04:23.954 request_id=GHNTqNydzlLkEikAAHLB [error] Error fetching assessment 19245 for user 9422: Missing Password. (status: forbidden).
01:04:23.956 request_id=GHNTqNy38vDkEikAAHMB [error] Failed to retrieve assessment 19245 for user 9316: forbidden - Missing Password.
.01:04:23.956 request_id=GHNTqNy38vDkEikAAHMB [error] Error fetching assessment 19245 for user 9420: Missing Password. (status: forbidden).
...01:04:25.358 request_id=GHNTqTBRtO9Yv4sAAFlC [error] Cannot finalize submission 17026 - some questions have not been attempted
01:04:25.358 request_id=GHNTqTBRtO9Yv4sAAFlC [error] Error submitting assessment 19369 for user 9482: Some questions have not been attempted (status: bad_request).
.......01:04:27.967 request_id=GHNTqcvm2EuzRw0AAHlB [error] User record not found for user 9446 in course 38770
...01:04:29.003 request_id=GHNTqgmUtGCHonMAAHrB [error] Cannot finalize submission 17437 - assessment has already been submitted
01:04:29.003 request_id=GHNTqgmUtGCHonMAAHrB [error] Error submitting assessment 19772 for user 9605: Assessment has already been submitted (status: forbidden).
...01:04:29.938 request_id=GHNTqkFUj-IRInoAAHwB [error] Submission not found for assessment 19897 and user 9648.
...01:04:31.015 request_id=GHNTqoF1TgfZgfgAAH2B [error] Assessment 20017 is not open for user 9676
01:04:31.015 request_id=GHNTqoF1TgfZgfgAAH2B [error] Failed to retrieve assessment 20017 for user 9551: forbidden - Assessment not open
.01:04:31.015 request_id=GHNTqoF1TgfZgfgAAH2B [error] Error fetching assessment 20017 for user 9676: Assessment not open (status: forbidden).
01:04:31.389 request_id=GHNTqpfCPPw3T-IAAH3B [error] Assessment 20057 not found or not published for user 9562
01:04:31.389 request_id=GHNTqpfCPPw3T-IAAH3B [error] Error fetching assessment 20057 for user 9688: Assessment not found (status: bad_request).
...........01:04:38.421 request_id=GHNTrDrvbxVNbcIAAKcB [error] Assessment 21093 is not open for user 10115.
.......01:04:43.267 request_id=GHNTrVu2y407QQsAAMRB [error] Failed to retrieve assessment 21480 for user 10155: forbidden - Invalid Password.
01:04:43.267 request_id=GHNTrVu2y407QQsAAMRB [error] Failed to unlock assessment 21480 for user 10300: Invalid Password. (status: forbidden).
01:04:43.270 request_id=GHNTrVvdee07QQsAAMSB [error] Failed to retrieve assessment 21480 for user 10154: forbidden - Invalid Password.
01:04:43.270 request_id=GHNTrVvdee07QQsAAMSB [error] Failed to unlock assessment 21480 for user 10299: Invalid Password. (status: forbidden).
01:04:43.272 request_id=GHNTrVwMwKQ7QQsAAMTB [error] Failed to retrieve assessment 21480 for user 10152: forbidden - Invalid Password.
01:04:43.272 request_id=GHNTrVwMwKQ7QQsAAMTB [error] Failed to unlock assessment 21480 for user 10297: Invalid Password. (status: forbidden).
..01:04:44.025 request_id=GHNTrYjuj3Jl6G8AAMVB [error] Submission not found for assessment 21521 and user 10333.
.........01:04:46.603 request_id=GHNTriKR2RuRJEwAAMyB [error] Submission 19212 is not in a submitted state
.01:04:46.603 request_id=GHNTriKR2RuRJEwAAMyB [error] Submission 19212 has not been submitted
.......01:04:47.098 request_id=GHNTrkAdRI3ihYoAAM-B [error] Assessment for submission 19264 is not open
...01:04:47.174 request_id=GHNTrkSVrEKsiWMAAM_B [error] User 10490 is not allowed to publish submission 19271
.01:04:47.174 request_id=GHNTrkSVrEKsiWMAAM_B [error] User 10490 is not allowed to unpublish grading for submission 19271
...01:04:47.260 request_id=GHNTrkmydNhSt2UAANCB [error] Grading for submission 19279 has already been published
......................01:04:48.831 request_id=GHNTrqdXIXvzkYkAANTB [error] User 10641 is not allowed to publish submission 19398
.01:04:48.831 request_id=GHNTrqdXIXvzkYkAANTB [error] User 10641 is not allowed to publish grading for submission 19398
01:04:48.862 request_id=GHNTrqlEC4746yAAANUB [error] Submission 19401 has already been attempted
.01:04:48.895 request_id=GHNTrqsuBJjPRD0AANVB [error] User 10654 is not allowed to unsubmit submission 19404
.............
Finished in 92.1 seconds (3.7s async, 88.3s sync)
943 tests, 21 failures, 7 invalid
